services:
  spin-clouddriver:
    container_name: spin-clouddriver
    environment:
      SPRING_PROFILES_ACTIVE: local
    image: spinnaker/clouddriver
    volumes:
      - ./config/clouddriver.yml:/opt/spinnaker/config/clouddriver.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
      - ./serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount
#    links:
    depends_on:
      - spin-redis
    ports:
      - "7002:7002"
    networks:
      network:
        ipv4_address: 10.5.0.15        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-deck:
    container_name: spin-deck
    environment:
      - PROTOCOL=http
      - AUTH_ENABLED=false
      - FIAT_ENABLED=false
      - API_HOST=http://192.168.33.2:8084
    image: spinnaker/deck
    volumes:
      - ./config/settings.js:/opt/spinnaker/config/settings.js
    ports:
      - "9000:9000"
    networks:
      network:
        ipv4_address: 10.5.0.14        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-echo:
    container_name: spin-echo
    environment:
      #JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      #JAVA 11 remove UseCGroupMemoryLimitForHeap
      JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:MaxRAMFraction=2
      SPRING_PROFILES_ACTIVE: local
    image: spinnaker/echo
    volumes:
      - ./config/echo.yml:/opt/spinnaker/config/echo.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    ports:
      - "8089:8089"
    depends_on:
      - spin-front50
      - spin-orca
    networks:
      network:
        ipv4_address: 10.5.0.13        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-front50:
    container_name: spin-front50
    environment:
      #JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      #JAVA 11 remove UseCGroupMemoryLimitForHeap
      JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:MaxRAMFraction=2
    image: spinnaker/front50
    volumes:
      - ./config/front50.yml:/opt/spinnaker/config/front50.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    ports:
      - "8080:8080"
    depends_on:
      - spin-redis
      - spin-mysql
    networks:
      network:
        ipv4_address: 10.5.0.12        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-gate:
    container_name: spin-gate
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    image: spinnaker/gate
    volumes:
        - ./config/gate.yml:/opt/spinnaker/config/gate.yml
        - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    depends_on:
      - spin-redis
      - spin-clouddriver
      - spin-echo
      - spin-front50
      - spin-orca
      - spin-rosco
    ports:
      - "8084:8084"
    networks:
      network:
        ipv4_address: 10.5.0.11        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-igor:
    container_name: spin-igor
    image: spinnaker/igor
    volumes:
      - ./config/config/igor.yml:/opt/spinnaker/config/igor.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    depends_on:
      - spin-redis
      - spin-echo
    ports:
      - "8088:8088"
    networks:
      network:
        ipv4_address: 10.5.0.10        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-orca:
    container_name: spin-orca
    environment:
      #JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      #JAVA 11 remove UseCGroupMemoryLimitForHeap
      JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:MaxRAMFraction=2
      SPRING_PROFILES_ACTIVE: local
    image: spinnaker/orca
    volumes:
      - ./config/orca.yml:/opt/spinnaker/config/orca.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
      - ./config/plugins.yml:/opt/spinnaker/config/plugins.yml
    depends_on:
      - spin-redis
      - spin-clouddriver
      - spin-front50
      - spin-rosco
    ports:
      - "8083:8083"
    networks:
      network:
        ipv4_address: 10.5.0.9        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-redis:
    container_name: spin-redis
    image: redis:4.0.12-alpine
    environment:
      MASTER: true
    ports:
      - "6379:6379"
    networks:
      network:
        ipv4_address: 10.5.0.8        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-rosco:
    container_name: spin-rosco
    image: spinnaker/rosco
    volumes:
      - ./config/rosco.yml:/opt/spinnaker/config/rosco.yml
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    depends_on:
      - spin-redis
    ports:
      - "8087:8087"
    environment:
      #JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      #JAVA 11 remove UseCGroupMemoryLimitForHeap
      JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:MaxRAMFraction=2
    networks:
      network:
        ipv4_address: 10.5.0.7        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-fiat:
    container_name: spin-fiat
    image: spinnaker/fiat
    volumes:
      - ./config/spinnaker.yml:/opt/spinnaker/config/spinnaker.yml
    depends_on:
      - spin-redis
      - spin-clouddriver
      - spin-front50
    ports:
      - "7003:7003"
    networks:
      network:
        ipv4_address: 10.5.0.6        
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5" 
  spin-mysql:
    container_name: spin-mysql
    image: mysql:5.7.22
    #    command: sh -c 'exec mysql -uroot --password=spinnaker' < sql/front50_mysql.sql
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    #command: --init-file sql/front50_mysql.sql
    volumes:
      - ./sql/front50_mysql.sql:/docker-entrypoint-initdb.d/front50_mysql.sql
   #   - ./config/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: spinnaker
      TZ: Asia/Shanghai
    networks:
      network:
        ipv4_address: 10.5.0.5
    extra_hosts:
      - "spin-clouddriver:10.5.0.15"
      - "spin-deck:10.5.0.14"
      - "spin-echo:10.5.0.13"
      - "spin-front50:10.5.0.12"
      - "spin-gate:10.5.0.11"
      - "spin-igor:10.5.0.10"
      - "spin-orca:10.5.0.9"
      - "spin-redis:10.5.0.8"
      - "spin-rosco:10.5.0.7"
      - "spin-fiat:10.5.0.6"
      - "spin-mysql:10.5.0.5"
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
