spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: false

spinnaker:
  s3:
    rootFolder: front50
    enabled: false
  oracle:
    enabled: false
  gcs:
    rootFolder: front50
    enabled: false
  azs:
    enabled: false
  redis:
    host: spin-redis
    port: 6379
    enabled: true

#sql:
#  enabled: true
#  connectionPools:
#    default:
#      default: true
#      jdbcUrl: jdbc:mysql://spin-mysql:3306/front50
#      user: root
#      password: spinnaker
#  migration:
#    user: root
#    password: spinnaker
#    jdbcUrl: jdbc:mysql://spin-mysql:3306/front50

sql:
  enabled: true
  connectionPools:
    default:
      # additional connection pool parameters are available here,
      # for more detail and to view defaults, see:
      # https://github.com/spinnaker/kork/blob/master/kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/ConnectionPoolProperties.kt
      default: true
      jdbcUrl: jdbc:mysql://spin-mysql:3306/front50
      user: front50_service
      # password: depending on db auth and how spinnaker secrets are managed
  migration:
    user: front50_migrate
    jdbcUrl: jdbc:mysql://spin-mysql:3306/front50

server:
  port: ${services.front50.port:8080}
  address: ${services.front50.host:localhost}

cassandra:
  enabled: false

hystrix:
  command:
    default.execution.isolation.thread.timeoutInMilliseconds: 15000
  threadpool:
    DefaultNotificationDAO:
      coreSize: 25
      maxQueueSize: 100
    DefaultPipelineDAO:
      coreSize: 25
      maxQueueSize: 100

spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml